"""Export the FastAPI OpenAPI schema to docs/openapi.json."""

from __future__ import annotations

import json
from pathlib import Path

from api.main import create_app


def main() -> None:
    """Write the OpenAPI document generated by the application."""

    output = Path("docs/openapi.json")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()

